# Generated by Django 3.1.13 on 2021-08-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('initial_moisture', models.IntegerField(max_length=3)),
                ('final_moisture', models.IntegerField(max_length=3)),
                ('bulk_density', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='DryerArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency', models.DecimalField(decimal_places=3, max_digits=4)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partial_pressure', models.IntegerField(max_length=6)),
                ('heat_capacity', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drying_time', models.DurationField(default='24:00:00')),
                ('air_density', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensionless_param', models.DecimalField(decimal_places=2, max_digits=3)),
                ('boiling_point', models.IntegerField(max_length=3)),
                ('freezing_point', models.IntegerField(max_length=1)),
                ('radiation_intensity', models.IntegerField(max_length=3)),
                ('solar_constant', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Vaporization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_gass_constant', models.DecimalField(decimal_places=1, max_digits=4)),
                ('vapour_gass_constant', models.DecimalField(decimal_places=1, max_digits=4)),
                ('boiling_point', models.IntegerField(max_length=3)),
                ('critical_pressure', models.IntegerField(max_length=8)),
                ('critical_temperature', models.IntegerField(max_length=3)),
            ],
        ),
    ]
