# Generated by Django 3.1.13 on 2021-08-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='bulk_density',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='final_moisture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='initial_moisture',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='heat_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pressure',
            name='partial_pressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='boiling_point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='freezing_point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='radiation_intensity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='solar_constant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaporization',
            name='boiling_point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaporization',
            name='critical_pressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vaporization',
            name='critical_temperature',
            field=models.IntegerField(),
        ),
    ]
