# Generated by Django 3.1.13 on 2021-08-05 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_chimney'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=4)),
                ('value', models.FloatField()),
                ('equation', models.CharField(choices=[('AF', 'airflow'), ('AV', 'air volume'), ('VZ', 'vaporization'), ('FR', 'flow rate'), ('CA', 'collector area'), ('CN', 'chimney'), ('DB', 'drying bed')], max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='crop',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
