# Generated by Django 3.1.13 on 2021-08-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_auto_20210805_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='equation',
            field=models.CharField(choices=[('airflow', 'Airflow'), ('air volume', 'Air Volume'), ('vaporization', 'Vaporization'), ('flow rate', 'Flow Rate'), ('collector area', 'Collector Area'), ('chimney', 'Chimney'), ('drying bed', 'Drying Bed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddConstraint(
            model_name='coefficient',
            constraint=models.UniqueConstraint(fields=('coefficient', 'equation'), name='common_coefficients'),
        ),
    ]
