# Generated by Django 3.1.13 on 2021-08-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_auto_20210805_2120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chimney',
        ),
        migrations.DeleteModel(
            name='DryerArea',
        ),
        migrations.DeleteModel(
            name='Pressure',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.DeleteModel(
            name='Vaporization',
        ),
    ]
