# Generated by Django 3.1.13 on 2021-08-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_auto_20210805_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coefficient',
            old_name='value',
            new_name='equivalent',
        ),
    ]
