# Generated by Django 3.1.13 on 2021-08-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0007_auto_20210810_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficient',
            name='units',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
