# Generated by Django 3.1.13 on 2021-09-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0008_coefficient_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='symbol',
            field=models.CharField(max_length=12),
        ),
    ]
