# Generated by Django 3.1.13 on 2021-09-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0009_auto_20210902_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='symbol',
            field=models.CharField(max_length=16),
        ),
    ]
