# Generated by Django 3.1.13 on 2021-07-31 12:25

import agriceng.solardryers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dryer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', 'Small'), ('LA', 'Large')], max_length=2)),
                ('version', models.CharField(choices=[('SI', 'Simple'), ('IM', 'Improved')], max_length=2)),
                ('diagram', models.ImageField(upload_to=agriceng.solardryers.models.dryer_directory_path)),
                ('construct', models.ImageField(upload_to=agriceng.solardryers.models.dryer_directory_path)),
                ('variation', models.ImageField(blank=True, upload_to=agriceng.solardryers.models.dryer_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=256)),
                ('dryer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solardryers.dryer')),
            ],
        ),
    ]
