# Generated by Django 3.1.13 on 2021-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solardryers', '0002_auto_20210731_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(max_length=256),
        ),
    ]
