# Generated by Django 3.1.13 on 2021-07-31 18:07

import agriceng.solardryers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solardryers', '0003_auto_20210731_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dryer',
            options={'ordering': ['-size', '-version']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['dryer', 'created', 'modified']},
        ),
        migrations.AlterField(
            model_name='dryer',
            name='construct',
            field=models.ImageField(blank=True, upload_to=agriceng.solardryers.models.dryer_directory_path),
        ),
    ]
